/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as idoContractSol from "./IdoContract.sol";
export type { idoContractSol };
import type * as samples from "./samples";
export type { samples };
export type { Staking } from "./Staking";
