// @ts-nocheck
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interface from './interface';
export type { interface };
export type { Staking20 } from './Staking20';
