/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iIdoContractSol from "./IIdoContract.sol";
export { IStaking__factory } from "./IStaking__factory";
