/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  CurrencyTransferLib,
  CurrencyTransferLibInterface,
} from "../../../../@thirdweb-dev/contracts/lib/CurrencyTransferLib";

const _abi = [
  {
    inputs: [],
    name: "NATIVE_TOKEN",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60f6610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c806331f7d964146038575b600080fd5b603e6052565b6040516049919060a7565b60405180910390f35b73eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee81565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000609382606a565b9050919050565b60a181608a565b82525050565b600060208201905060ba6000830184609a565b9291505056fea26469706673582212208744c9da35fd0735d66395455adca7dad081a872424619a9c626e932dcada17c64736f6c63430008120033";

type CurrencyTransferLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CurrencyTransferLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CurrencyTransferLib__factory extends ContractFactory {
  constructor(...args: CurrencyTransferLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<CurrencyTransferLib> {
    return super.deploy(overrides || {}) as Promise<CurrencyTransferLib>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): CurrencyTransferLib {
    return super.attach(address) as CurrencyTransferLib;
  }
  override connect(signer: Signer): CurrencyTransferLib__factory {
    return super.connect(signer) as CurrencyTransferLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CurrencyTransferLibInterface {
    return new utils.Interface(_abi) as CurrencyTransferLibInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CurrencyTransferLib {
    return new Contract(address, _abi, signerOrProvider) as CurrencyTransferLib;
  }
}
