/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IIDOContract,
  IIDOContractInterface,
} from "../../../../contracts/interface/IIdoContract.sol/IIDOContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "depositTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IIDOContract__factory {
  static readonly abi = _abi;
  static createInterface(): IIDOContractInterface {
    return new utils.Interface(_abi) as IIDOContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IIDOContract {
    return new Contract(address, _abi, signerOrProvider) as IIDOContract;
  }
}
