// @ts-nocheck
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as idoContractSol from "./IdoContract.sol";
export * as interface from "./interface";
export * as samples from "./samples";
export { Dividend__factory } from "./Dividend__factory";
export { Staking__factory } from "./Staking__factory";
