/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMulticall__factory } from "./IMulticall__factory";
export { IStaking20__factory } from "./IStaking20__factory";
