/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
// @ts-ignore
export * as interface from "./interface";
export { Staking20__factory } from "./Staking20__factory";
