import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import PageTopHeading from "../components/common/PageTopHeading";
import {
  ApplyForIDOHeading,
  FindUsInSocial,
  IDOList,
} from "../components/containers/project-list/components";
import PageLayout from "../components/templates/PageLayout";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <PageTopHeading />
        <IDOList />
        <ApplyForIDOHeading />
        <FindUsInSocial />
      </PageLayout>
    </>
  );
};

export default Home;
