/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iIdoContractSol from "./IIdoContract.sol";
export type { iIdoContractSol };
export type { IStaking } from "./IStaking";
