// @ts-nocheck
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as idoContractSol from "./IdoContract.sol";
export type { idoContractSol };
import type * as interface from "./interface";
export type { interface };
import type * as samples from "./samples";
export type { samples };
export type { Dividend } from "./Dividend";
export type { Staking } from "./Staking";
